Add matugen for dynamic color themes
Integrate with ghostty, hyprland, and waybar.

diff --git a/home/swww/bin/cw b/home/swww/bin/cw
--- a/home/swww/bin/cw
+++ b/home/swww/bin/cw
@@ -8,3 +8,22 @@ WALLPAPER=$(find "$WALLPAPER_DIR" -mindepth 1 -maxdepth 1 -type f -name "*.jpeg"
 
 # Apply the selected wallpaper
 swww img "$WALLPAPER" --transition-type fade --transition-fps 120 --transition-duration 5
+
+# Downsize for sampling
+magick "$WALLPAPER" -resize 400x400\> /tmp/matugen_sample.jpg
+
+# Make color palette from sampled wallpaper
+if matugen image /tmp/matugen_sample.jpg --type scheme-fidelity; then
+  # Reload waybar styles
+  cp ~/.dotfiles/home/waybar/style.css ~/.dotfiles/home/waybar/style.css.tmp
+  mv ~/.dotfiles/home/waybar/style.css.tmp ~/.dotfiles/home/waybar/style.css
+
+  # Reload ghostty styles
+  killall -SIGUSR2 ghostty
+
+  # Reload hyprland styles
+  hyprctl reload
+else
+  echo "Matugen failed to parse the image. Keeping current colors."
+  exit 1
+fi
